# Generated by Django 2.0.2 on 2019-01-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField()),
                ('action', models.CharField(max_length=300)),
                ('value2', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
    ]
